version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18v2lszqi2ry0"
s3_prefix = "sam-sample"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true